[general]
working_directory = "~/workspace"

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 10, y = 10 }
startup_mode = "Maximized"
title = "xhell"
dynamic_title = false

[scrolling]
history = 10000
multiplier = 3

[font]
size = 15.0
offset = { x = 1, y = 5 }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[bell]
animation = "EaseOutExpo"
duration = 200
